// username - req
// email - req
// videoid - unique (should be generated by mongodb)
// video url - not necessarily req , will later be updated
// thumbmail url - not necessarily req , will later be updated
// transcode status - default , NotReceived


import mongoose from "mongoose";

const videoSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    trim: true,
  },
  email: {
    type: String,
    required: true,
    lowercase: true,
    trim: true,
  },
  title: {
    type: String,
    required: true,
    trim: true,
  },
  description: {
    type: String,
    required: true,
    trim: true,
  },
  videoUrl: {
    type: String,
    default: '', // can be updated later
  },
  thumbnailUrl: {
    type: String,
    default: '', // can be updated later
  },
  transcodeStatus: {
    type: String,
    enum: ['NotReceived', 'Processing', 'Completed', 'Failed'],
    default: 'NotReceived',
  },
}, { timestamps: true });

const Video = mongoose.model('Video', videoSchema);

export default Video;
